language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

language: php
php:
  - 5.5

install:
  - composer install --dev

notifications:
  irc:
    - "irc.pngn.co#dev"

